name: Continuous Integration - Vite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: cd electron && yarn install
      - run: yarn build:vite

    # Incorrect type. Expected "reusableWorkflowCallJob" means that the job is not a reusable workflow call job and to solve this issue, we need to
